---
# install snapd depending on os type

- name: installing snapd on redhat system
  import_tasks: snapd_redhat.yml
  when: ansible_os_family|lower == 'redhat'

- name: install snapd on debian system
  import_tasks: snapd_debian.yml
  when: ansible_os_family|lower == 'debian'

- name: enable snapd ensure it is started
  service:
    name: snapd.service
    enabled: yes
    state: started

# symlink required on CentOS 7 for classic confinement
- name: symlink /snap if redhat
  when: ansible_os_family|lower == 'redhat'
  become: yes
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link

- name: installing microk8s via snapd
  become: yes
  shell: snap install microk8s --classic
  register: command_result
  failed_when: "'error' in command_result.stderr"

#- name: enable the dns addon
#  # full path due to microk8s.enable not being in the path for ansible
#  shell: /snap/bin/microk8s.enable dns