---
- name: Installing epel and cpor plugin
  become: yes
  yum:
    name:
    - epel-release
    - yum-plugin-copr
    state: present

- name: enabling snapcore repo
  become: yes
  shell: yum copr enable ngompa/snapcore-el7 -y

- name: installing snapd
  become: yes
  yum:
    name: snapd
    state: present
