---
- name: ensure apt deps
  apt:
    update_cache: yes
    name:
    - apt-transport-https
    - curl
    - software-properties-common
    - ca-certificates
    state: present

- name: adding the docker apt key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  args:
    warn: false

- name: adding the google apt key
  shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  args:
    warn: false

- name: add docker repo
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: copy the kubernetes.list file for apt
  copy:
    src: kubernetes.list
    dest: /etc/apt/sources.list.d/kubernetes.list
    owner: root
    group: root
    mode: 0644

- name: install kubelet, kubeadm andkubectl
  apt:
    update_cache: yes
    name:
    - kubelet
    - kubeadm
    - kubectl
    - docker-ce=17.03.0~ce-0~ubuntu
    state: present

- name: prevent kubeadm from being updated
  shell: apt-mark hold kubelet kubeadm kubectl

- name: disable swap
  shell: swapoff -a

- name: disable swap in fstab
  shell: sed -e '/swap/s/^/#/g' -i /etc/fstab
  args:
    warn: false